actors:
  ysdyt:
    image_url: /images/actors/yutatatatata.jpg
    name: ysdyt
    url: https://twitter.com/yutatatatata
  Hyperion_13:
    image_url: /images/actors/Hyperion134.jpg
    name: Hyperion_13
    url: https://twitter.com/Hyperion134
  fujitako:
    image_url: /images/actors/fujitako03.jpg
    name: fujitako
    url: https://twitter.com/fujitako03
  saturatedB:
    image_url: /images/actors/hanaco117.jpg
    name: saturatedB
    url: https://twitter.com/hanaco117
  かっつん:
    image_url: /images/actors/banbutsu_th.jpg
    name: かっつん
    url: https://twitter.com/banbutsu_th
  にのぴら:
    image_url: /images/actors/nino_pira.jpg
    name: にのぴら
    url: https://twitter.com/nino_pira
  Yuya Matsumura:
    image_url: /images/actors/yu__ya4.jpg
    name: Yuya Matsumura
    url: https://twitter.com/yu__ya4
  Kei Inoue:
    image_url: /images/actors/KeiInoue.jpg
    name: Kei Inoue
    url:
  t.noguchi:
    image_url: /images/actors/tnoguchi15.jpg
    name: t.noguchi
    url: https://twitter.com/tnoguchi15
  おおたまん:
    image_url: /images/actors/ohtaman.jpg
    name: おおたまん
    url: https://twitter.com/ohtaman
  Kimitaka Koyama:
    image_url: /images/actors/kimitaka_koyama.jpg
    name: Kimitaka Koyama
    url: https://twitter.com/kimitaka_koyama
  Yuki Ieiri:
    image_url: /images/actors/YukiIeiri.jpg
    name: Yuki Ieiri
    url: https://github.com/ieiriyuki
  Yukihiro Konya:
    image_url: /images/actors/YukihiroKonya.jpg
    name: Yukihiro Konya
    url: https://speakerdeck.com/yukihirokonya
  Shota Okazaki:
    image_url: /images/actors/ShotaOkazaki.jpg
    name: Shota Okazaki
    url: 
  Kurihara:
    image_url: /images/actors/RioKurihara.jpg
    name: Kurihara
    url: https://www.slideshare.net/_Rio_
  ゆうちょ:
    image_url: /images/actors/yucho147.jpg
    name: ゆうちょ
    url: https://twitter.com/yucho147
  Daigo:
    image_url: /images/actors/daigo_hirooka.jpg
    name: Daigo
    url: https://twitter.com/daigo_hirooka
  佐藤 由将:
    image_url: /images/actors/usksatoo.jpg
    name: 佐藤 由将
    url: https://twitter.com/usksatoo
  nyker_goto:
    image_url: /images/actors/nyker_goto.jpg
    name: nyker_goto
    url: https://twitter.com/nyker_goto
  Takami Sato:
    image_url: /images/actors/tkm2261.jpg
    name: Takami Sato
    url: https://twitter.com/tkm2261
  Yohei Sugawara:
    image_url: /images/actors/ywara93.jpg
    name: Yohei Sugawara
    url: https://twitter.com/ywara93
  Shibata:
    image_url: /images/actors/alice.png
    name: Shibata
    url:
  Sorami Hisamoto:
    image_url: /images/actors/sorami.jpg
    name: Sorami Hisamoto
    url: https://twitter.com/sorami
  Takafumi Kusano:
    image_url: /images/actors/TakafumiKusano.jpg
    name: Takafumi Kusano
    url: https://www.facebook.com/zaakya
  u++:
    image_url: /images/actors/u++.png
    name: u++
    url: https://twitter.com/upura0
  Umepon:
    image_url: /images/actors/umepon.jpg
    name: Umepon
    url: https://twitter.com/shunji_umetani
  shu O.:
    image_url: /images/actors/alice.png
    name: shu O.
    url: https://twitter.com/shu_1024_z80
  Makoto Hyodo:
    image_url: /images/actors/MakotoHyodo.jpg
    name: Makoto Hyodo
    url: 
  城戸 (Legalscape):
    image_url: /images/actors/p_km.png
    name: 城戸 (Legalscape)
    url: https://twitter.com/p_km
  Ko Fujita:
    image_url: /images/actors/6km6km.jpeg
    name: Ko Fujita
    url: https://twitter.com/6km6km
  タカヤナギサン:
    image_url: /images/actors/_stakaya.jpeg
    name: タカヤナギサン
    url: https://twitter.com/_stakaya
  nishiba:
    image_url: /images/actors/m_nishiba.jpeg
    name: nishiba
    url: https://twitter.com/m_nishiba
author: 白金鉱業
description: データサイエンスやAI界隈の話題を中心に、BrainPad社のデータサイエンティスト有志メンバーがアツいと感じていることを自由に話すポッドキャスト番組です。
description_long: 白金鉱業.FMはBrainPad社のデータサイエンティスト有志メンバーによるポッドキャスト番組です。メンバー同士や、時に外部ゲストを交え、データ分析やAI界隈、または気の向くままに雑談などをざっくばらんに話しています。
email: shirokanekougyou@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-60961437-2
hashtag: 白金鉱業fm
itunes_podcast_url: https://podcasts.apple.com/jp/podcast/%E7%99%BD%E9%87%91%E9%89%B1%E6%A5%AD-fm/id1479033656
keywords: data science,AI
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 白金鉱業.FM
url: https://shirokane-kougyou.fm
