actors:
  ysdyt:
    image_url: /images/actors/ysdyt.jpg
    name: ysdyt
    url: https://twitter.com/yutatatatata
  Hyperion_13:
    image_url: /images/actors/Hyperion_13.jpg
    name: Hyperion_13
    url: https://twitter.com/Hyperion134
author: 白金鉱業
description: 白金鉱業メンバーがアツいと感じていることを自由に話すポッドキャスト番組です。
description_long: 白金鉱業メンバーによるポッドキャスト番組です。メンバー内や、外部のゲストをお招きして、データ分析やAI界隈についてその時々アツいと感じたことを分野を問わずざっくばらんに話しています。
email: shirokanekougyou@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: 白金鉱業fm
itunes_podcast_url:
keywords: data science,AI
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 白金鉱業.fm
url: https://shirokane-kougyou.fm
